### ISSUE TITLE
As a user, I want to comment on a course or prof, or a prof of a specific course, so that my comments can be most relevant.

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#22]
### Acceptance Criteria
- [x] Comment on a course in general #113 
- [x] Comment on a prof in general #114
- [x] Comment on a course with a specific prof #115
- [x] Pass unit test

**Comment by mstillman9** [comment]
Done.
