### ISSUE TITLE
As a User, I want to sign up and log in to the website, so I can have an identity when I browse the site.

### ISSUE THREAD

**Issue by kz882** [nyu-software-engineering/fall-2019-easy-nyu#23]
### Acceptance Criteria
- [x] Signup route for Express #55 
- [x] Unit Test for Signup Route #66 
- [x] Unit Test for Login Route #67 
- [x] Login Route for Express #65 
- [x] Create User Schema for MongoDB

**Comment by mstillman9** [comment]
Done.
