### ISSUE TITLE
As a user, I want to view all courses so that I can select to see details of a course

### ISSUE THREAD

**Issue by XuanzhengLin** [nyu-software-engineering/fall-2019-easy-nyu#57]
### Acceptance criteria
- [x] Comment on a course #58 
- [x] Write comment #59 
- [x] Store the comment within the course in database #60 
- [x] Unit Test for Course #51 
- [x] Unit Test for Comment #64 
- [x] Write backend code to display courses with most to least comments #70 #71
- [x] Write frontend code to display courses #69 
- [x] Add a comment for a course #161
- [x] Redesign course detail page #192

**Comment by mstillman9** [comment]
Done
