### ISSUE TITLE
As a user, I want to view comments for a specific prof so that I can have better understanding of his teaching style

### ISSUE THREAD

**Issue by hzzyy1997** [nyu-software-engineering/fall-2019-easy-nyu#74]
### Acceptance criteria
- [x] Comment on Professor #78
- [x] Store the comment within the Professor in database #77
- [x] Write frontend code to display Professors #102
- [x] Implement public prof search #142
- [x] Display each prof profile #139 
- [x] Display comments on each prof profile #162

**Comment by XuanzhengLin** [comment]
How does this differ from #57?

**Comment by mstillman9** [comment]
Done
